version: '1'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./db:/app/db
      - ./pdfs:/app/pdfs
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama-1

    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

volumes:
  ollama_data:
